// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOdMIBlD6U0D3GZiieVcL5J-tLSL1AtjE',
    appId: '1:150611467283:web:4fddb9e9793e24c52433e6',
    messagingSenderId: '150611467283',
    projectId: 'savingtracker-81f33',
    authDomain: 'savingtracker-81f33.firebaseapp.com',
    storageBucket: 'savingtracker-81f33.appspot.com',
    measurementId: 'G-FD5PVFX96L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjAqRbHSqeu3P0kyFETUDb9178kPmi4Nw',
    appId: '1:150611467283:android:2d8fd9d3015fb44b2433e6',
    messagingSenderId: '150611467283',
    projectId: 'savingtracker-81f33',
    storageBucket: 'savingtracker-81f33.appspot.com',
  );
}
